#pragma once
// The API a native (C++) module is compiled against.
//
// A native module is a shared library that `import` can load, so a binding to a
// C or C++ library doesn't mean rebuilding the interpreter. It exports two
// symbols and nothing else:
//
//     extern "C" const char* bee_native_abi();          // must return BEE_NATIVE_ABI
//     extern "C" int bee_module_init(bee::NativeModule*); // 0 on success
//
// and registers its functions on the NativeModule it is handed:
//
//     extern "C" int bee_module_init(bee::NativeModule* m) {
//         m->def("add", 2, [](bee::Interpreter&, std::vector<bee::Value>& a) {
//             return bee::Value(bee::native::num(a[0], "add", 0) +
//                               bee::native::num(a[1], "add", 1));
//         });
//         return 0;
//     }
//
// Then `import mymodule` binds those names, exactly like a `.bee` module.
//
// IMPORTANT: this is a C++ ABI, not a C one -- Value holds std::variant and
// std::shared_ptr, so a module must be built with the same compiler and standard
// library as the interpreter. `bee_native_abi()` catches version drift, not
// toolchain mismatch. Modules generated by `beegen` come with a build command
// that matches.
#include "bee_buffer.h"
#include "interpreter.hpp"

#include <cstdint>
#include <functional>
#include <limits>
#include <string>
#include <vector>

// Bumped whenever the shape of NativeModule or Value changes incompatibly.
#define BEE_NATIVE_ABI "bee-native-1"

namespace bee {

// Handed to bee_module_init(); everything defined on it becomes a member of the
// imported module.
class NativeModule {
public:
    NativeModule(Interpreter& interp, std::shared_ptr<Environment> env)
        : interp(interp), env_(std::move(env)) {}

    // Register a callable. `arity` is the exact argument count, or -1 for any.
    void def(const std::string& name, int arity,
             std::function<Value(Interpreter&, std::vector<Value>&)> fn) {
        auto b = std::make_shared<Builtin>();
        b->name = name;
        b->arity = arity;
        b->fn = std::move(fn);
        env_->define(name, Value(b));
    }

    // Register a value: an enum constant, a version string, a limit.
    void constant(const std::string& name, Value v) { env_->define(name, std::move(v)); }

    Interpreter& interp;

private:
    std::shared_ptr<Environment> env_;
};

// ---------------------------------------------------------------------------
// Argument conversion
// ---------------------------------------------------------------------------
// Helpers for the boundary between Bee values and C++ types. They throw
// RuntimeError on a mismatch, which the interpreter reports at the call site
// with a stack trace -- so a wrong argument from Bee code reads like any other
// runtime error, not a crash.
namespace native {

[[noreturn]] inline void argError(const char* who, int index, const char* expected,
                                 const std::string& got) {
    throw RuntimeError(std::string(who) + ": argument " + std::to_string(index + 1) +
                       " must be " + expected + ", got " + got);
}

inline const char* typeName(const Value& v) {
    if (v.isNil()) return "nil";
    if (v.isBool()) return "a bool";
    if (v.isNumber()) return "a number";
    if (v.isString()) return "a string";
    if (v.isList()) return "a list";
    if (v.isDict()) return "a dict";
    return "another type";
}

inline double num(const Value& v, const char* who, int index) {
    if (!v.isNumber()) argError(who, index, "a number", typeName(v));
    return v.asNumber();
}

inline bool boolean(const Value& v, const char* who, int index) {
    if (!v.isBool()) argError(who, index, "a bool", typeName(v));
    return v.asBool();
}

inline const std::string& str(const Value& v, const char* who, int index) {
    if (!v.isString()) argError(who, index, "a string", typeName(v));
    return v.asString();
}

// Integer conversion that refuses to silently truncate: a fractional or
// out-of-range value is a mistake worth reporting, not rounding away.
template <typename Int>
inline Int integer(const Value& v, const char* who, int index) {
    double d = num(v, who, index);
    if (d != (double)(long long)d)
        throw RuntimeError(std::string(who) + ": argument " + std::to_string(index + 1) +
                           " must be a whole number, got " + std::to_string(d));
    long long i = (long long)d;
    if ((double)i < (double)std::numeric_limits<Int>::min() ||
        (double)i > (double)std::numeric_limits<Int>::max())
        throw RuntimeError(std::string(who) + ": argument " + std::to_string(index + 1) +
                           " is out of range for this parameter");
    return (Int)i;
}

// ---------------------------------------------------------------------------
// Class hierarchies
// ---------------------------------------------------------------------------
// A handle carries the exact class it was made for, so a Derived handle would be
// rejected where a Base is wanted. Generated modules register the conversion --
// a real static_cast, so the pointer is adjusted correctly even under multiple
// inheritance -- and handlePtr() applies it.
using UpcastFn = void* (*)(void*);

struct Upcast {
    std::string from, to;
    UpcastFn convert;
};

inline std::vector<Upcast>& upcasts() {
    static std::vector<Upcast> registry;
    return registry;
}

inline void registerUpcast(const std::string& from, const std::string& to, UpcastFn convert) {
    upcasts().push_back({from, to, convert});
}

// Walk the registered conversions to get from `from` to `to`, applying each cast
// in turn. Returns null when there is no path.
inline void* applyUpcast(void* p, const std::string& from, const std::string& to, int depth = 0) {
    if (from == to) return p;
    if (depth > 8) return nullptr;   // cycles or an absurd hierarchy
    for (auto& u : upcasts()) {
        if (u.from != from) continue;
        void* next = u.convert(p);
        if (!next) continue;
        if (void* found = applyUpcast(next, u.to, to, depth + 1)) return found;
    }
    return nullptr;
}

// ---------------------------------------------------------------------------
// Opaque handles
// ---------------------------------------------------------------------------
// A pointer to a C++ object that Bee has no representation for is passed across
// as a small dict: {"__handle": <address>, "__type": "Foo"}. Keeping the type
// name means a handle from the wrong class is caught here instead of becoming a
// bad cast, and generated `.bee` wrappers can hide the dict entirely behind a
// normal-looking class.
inline Value makeHandle(const std::string& type, void* p) {
    auto d = std::make_shared<ValueDict>();
    (*d)["__handle"] = Value((double)(uintptr_t)p);
    (*d)["__type"] = Value(type);
    return Value(d);
}

inline void* handlePtr(const Value& v, const std::string& type, const char* who, int index) {
    if (!v.isDict()) argError(who, index, ("a " + type + " handle").c_str(), typeName(v));
    auto d = v.asDict();
    auto h = d->find("__handle");
    auto t = d->find("__type");
    if (h == d->end() || t == d->end() || !h->second.isNumber() || !t->second.isString())
        argError(who, index, ("a " + type + " handle").c_str(), "some other dict");
    auto address = (uintptr_t)h->second.asNumber();
    if (!address)
        throw RuntimeError(std::string(who) + ": argument " + std::to_string(index + 1) +
                           " is a " + t->second.asString() + " handle that has already been freed");
    const std::string& actual = t->second.asString();
    if (actual == type) return (void*)address;
    // A derived class is acceptable where a base is expected, via the registered
    // static_cast -- which is what makes an interface-based API (TensorRT,
    // ONNX Runtime) bindable at all.
    if (void* converted = applyUpcast((void*)address, actual, type)) return converted;
    argError(who, index, ("a " + type + " handle").c_str(), "a " + actual + " handle");
}

template <typename T>
inline T* handle(const Value& v, const std::string& type, const char* who, int index) {
    return static_cast<T*>(handlePtr(v, type, who, index));
}

// ---------------------------------------------------------------------------
// Buffers -- bulk data, without a copy
// ---------------------------------------------------------------------------
// A Bee buffer becomes a BeeBuffer (see bee_buffer.h) pointing at the same
// memory, so an image or a tensor crosses the boundary as one pointer. The view
// is valid for the duration of the call only.
inline int dtypeCode(DType t) {
    switch (t) {
        case DType::F32: return BEE_DTYPE_F32;
        case DType::F64: return BEE_DTYPE_F64;
        case DType::I8:  return BEE_DTYPE_I8;
        case DType::U8:  return BEE_DTYPE_U8;
        case DType::I16: return BEE_DTYPE_I16;
        case DType::U16: return BEE_DTYPE_U16;
        case DType::I32: return BEE_DTYPE_I32;
        case DType::I64: return BEE_DTYPE_I64;
    }
    return BEE_DTYPE_F64;
}

inline BeeBuffer bufferView(const Value& v, const char* who, int index) {
    if (!v.isBuffer()) argError(who, index, "a buffer", typeName(v));
    auto b = v.asBuffer();
    if (b->shape.size() > BEE_BUFFER_MAX_DIMS)
        throw RuntimeError(std::string(who) + ": buffers with more than " +
                           std::to_string(BEE_BUFFER_MAX_DIMS) + " dimensions are not supported");
    BeeBuffer out{};
    out.data = b->bytes.empty() ? nullptr : (void*)b->bytes.data();
    out.bytes = (long long)b->bytes.size();
    out.dtype = dtypeCode(b->dtype);
    out.ndim = (int)b->shape.size();
    for (size_t i = 0; i < b->shape.size(); ++i) out.shape[i] = b->shape[i];
    return out;
}

// Allocate a Bee buffer from native code -- for a shim that has to hand back
// data whose size it only knows at run time.
inline Value makeBuffer(DType dtype, const std::vector<long long>& shape) {
    auto b = std::make_shared<Buffer>();
    b->dtype = dtype;
    b->shape = shape;
    size_t n = shape.empty() ? 1 : 1;
    for (long long d : shape) n *= (size_t)d;
    b->bytes.assign(n * Buffer::widthOf(dtype), 0);
    return Value(b);
}

// ---------------------------------------------------------------------------
// Calling back into Bee
// ---------------------------------------------------------------------------
// Libraries that report progress or log through a callback (TensorRT's ILogger,
// ONNX Runtime's logging function, OpenCV's trackbars) need to call *into*
// Bee. Hold the callable in a shim object and invoke it through this.
//
// The GIL must be held. It already is when the call came from Bee code; a
// callback arriving on a thread the library created must take it first -- see
// GilLock below.
class Callback {
public:
    Callback() = default;
    Callback(Interpreter& interp, Value fn, const char* who, int index)
        : interp_(&interp), fn_(std::move(fn)) {
        if (!fn_.isCallable()) argError(who, index, "a function", typeName(fn_));
    }

    bool valid() const { return interp_ != nullptr; }

    Value operator()(std::vector<Value> args) const {
        if (!interp_) throw RuntimeError("this callback was never set");
        return interp_->callValue(fn_, args, 0);
    }

    Value operator()() const { return (*this)({}); }

private:
    Interpreter* interp_ = nullptr;
    Value fn_;
};

inline Callback callback(Interpreter& interp, const Value& v, const char* who, int index) {
    return Callback(interp, v, who, index);
}

// Take the GIL for a scope. Needed when a library calls a callback on its own
// thread: running Bee code without it would race the interpreter.
struct GilLock {
    Interpreter& interp;
    explicit GilLock(Interpreter& i) : interp(i) { interp.gilAcquire(); }
    ~GilLock() { interp.gilRelease(); }
    GilLock(const GilLock&) = delete;
    GilLock& operator=(const GilLock&) = delete;
};

// Hand the GIL back while a long native call runs, so other Bee threads make
// progress. The mirror image of GilLock.
struct GilOff {
    Interpreter& interp;
    explicit GilOff(Interpreter& i) : interp(i) { interp.gilRelease(); }
    ~GilOff() { interp.gilAcquire(); }
    GilOff(const GilOff&) = delete;
    GilOff& operator=(const GilOff&) = delete;
};

// ---------------------------------------------------------------------------
// Lists
// ---------------------------------------------------------------------------
inline std::shared_ptr<ValueList> listArg(const Value& v, const char* who, int index) {
    if (!v.isList()) argError(who, index, "a list", typeName(v));
    return v.asList();
}

template <typename T, typename Convert>
inline std::vector<T> toVector(const Value& v, const char* who, int index, Convert convert) {
    std::vector<T> out;
    for (auto& item : *listArg(v, who, index)) out.push_back(convert(item, who, index));
    return out;
}

template <typename T, typename Convert>
inline Value fromVector(const std::vector<T>& in, Convert convert) {
    auto out = std::make_shared<ValueList>();
    out->reserve(in.size());
    for (auto& item : in) out->push_back(convert(item));
    return Value(out);
}

}  // namespace native
}  // namespace bee

extern "C" {
// Implemented by every native module. Declared here so a module that forgets one
// fails to compile rather than failing to load.
const char* bee_native_abi();
int bee_module_init(bee::NativeModule* m);
}
